services:
  - type: web
    name: eye-disease-classifier-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_api.py
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PORT
        value: 8000
